name: .NET MAUI Windows Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x  # Ensure this matches your project's .NET version

      - name: Install .NET MAUI Workloads
        run: dotnet workload restore

      - name: Restore dependencies for Windows
        run: dotnet restore --runtime win-x64

      - name: Build Windows solution
        run: dotnet build --configuration Release --no-restore --framework net8.0-windows10.0.19041.0

      - name: Run Windows NUnit Tests
        run: dotnet test --no-build --verbosity normal --framework net8.0-windows10.0.19041.0
