name: .NET NUnit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x  # Adjust based on your .NET version

      - name: Install .NET MAUI Workloads
        run: dotnet workload restore

      - name: Restore dependencies with specific RIDs
        run: dotnet restore --runtime win-x64 --runtime maccatalyst-arm64

      - name: Build the solution
        run: dotnet build --configuration Release --no-restore

      - name: Run NUnit Tests
        run: dotnet test --no-build --verbosity normal
