name: .NET MAUI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install .NET MAUI Workloads
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore

      - name: Build MAUI project
        run: dotnet build --configuration Release --framework net8.0-windows10.0.19041.0

  build-android:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install .NET MAUI and Android Workloads
        run: |
          dotnet workload install maui
          dotnet workload install android

      - name: Restore dependencies
        run: dotnet restore

      - name: Build MAUI project for Android
        run: dotnet build --configuration Release --framework net8.0-android
