name: .NET MAUI Windows Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x  # Ensure this matches your project's .NET version

      - name: Install .NET MAUI Workloads
        run: dotnet workload restore

      - name: Restore dependencies with Runtime Identifier
        run: dotnet restore --runtime win-x64
        working-directory: ./MauiApp

      - name: Build MAUI Project for Windows
        run: dotnet build --configuration Release --no-restore --framework net8.0-windows10.0.19041.0
        working-directory: ./MauiApp

