jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Install .NET MAUI Workloads
        run: dotnet workload install maui

      - name: Restore and build for Windows
        run: |
          dotnet restore ./MauiApp -r win10-x64 -f net8.0-windows10.0.19041.0
          dotnet build ./MauiApp --configuration Release --no-restore -r win10-x64 -f net8.0-windows10.0.19041.0
