name: .NET MAUI Windows Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install .NET MAUI Workloads
        run: dotnet workload install maui

      - name: Restore dependencies with RuntimeIdentifier
        run: |
          dotnet restore ./MauiApp --property:RuntimeIdentifier=win10-x64 --property:TargetFramework=net8.0-windows10.0.19041.0

      - name: Build MAUI Project for Windows
        run: |
          dotnet build ./MauiApp --configuration Release --no-restore --property:RuntimeIdentifier=win10-x64 --property:TargetFramework=net8.0-windows10.0.19041.0

      - name: Build NUnit Test Project
        run: |
          dotnet build ./UITests.Windows --configuration Release --no-restore

      - name: Run NUnit Tests
        run: |
          dotnet test ./UITests.Windows --no-build --verbosity normal
