name: Build .NET MAUI Windows App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install .NET SDK (specify .NET 8.0)
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Ensure .NET 8 SDK is installed

      # Step 3: Restore the NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project (for Windows only)
      - name: Build the project for Windows
        run: dotnet build --configuration Release --framework net8.0-windows10.0.19041.0
